title: Deng's Computational Mathematics Lab @ ANU
description: Deng's Computational Mathematics Lab @ ANU
author: Quanling Deng
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
